### ISSUE TITLE
Centre align image, add text to HTML page on meme render

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/spongebob-as-a-service#4]
Self-explanatory, need to centre align the image and have the functionality to pass content for the body.

**Comment by Gauravkain** [comment]
I want to contribute.

**Comment by aditeyabaral** [comment]
Sure, go ahead :)

**Comment by aditeyabaral** [comment]
Hello @Gauravkain 
Any updates on this?

**Comment by aditeyabaral** [comment]
No updates on this, un-assigning
